# Generated by Django 6.1.1 on 2026-09-09 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_identitysyncrequestlog_user_active_and_more'),
        ('appointments', '0003_appointment_call_link_appointment_modality_and_more'),
        ('clients', '0002_client_administrative_notes_client_birth_date_and_more'),
        ('professionals', '0002_alter_professional_options_alter_specialty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_record', to='appointments.appointment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_clinical_records', to='accounts.user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='clients.client')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='professionals.professional')),
            ],
            options={
                'db_table': 'clinical_records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['client', 'recorded_at'], name='idx_clinrec_client_time')],
            },
        ),
    ]
