# Generated by Django 6.1.1 on 2026-09-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitySyncRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('firebase_uid', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=10)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_sync_request_log',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
