# Generated by Django 6.1.1 on 2026-09-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name_plural': 'specialties'},
        ),
    ]
