# Generated by Django 6.1.1 on 2026-09-03 16:58

import apps.appointments.models
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clients', '0001_initial'),
        ('professionals', '0002_alter_professional_options_alter_specialty_options'),
        ('services', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), expressions=[('professional', '='), (apps.appointments.models.TsTzRange('starts_at', 'ends_at'), '&&')], name='exclude_overlapping_appointments'),
        ),
    ]
