# Generated by Django 6.1.1 on 2026-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_exclude_overlapping_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='modality',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('IN_PERSON', 'Presencial'), ('HYBRID', 'Híbrido')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
