# Generated by Django 6.1.1 on 2026-09-09 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_call_link_appointment_modality_and_more'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='packages.package'),
        ),
    ]
